/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JavaScript config object */
export interface JsInterceptShortcut {
  modifierMask: number
  keycode: number
}
export interface JsFnKeyConfig {
  /** Whether to intercept system behavior (only configured shortcuts are blocked) */
  interceptSystem?: boolean
  /** When intercept on: block the FN key itself (user has "FN" shortcut) */
  interceptFnKey?: boolean
  /** When intercept on: consume FN+key events entirely for these keycodes (FN+key shortcuts) */
  interceptKeyCodesWhenFnDown?: Array<number>
  /** Non-FN shortcuts to intercept: (modifier_mask, keycode) pairs */
  interceptShortcuts?: Array<JsInterceptShortcut>
  /** Double tap detection interval in milliseconds */
  doubleTapInterval?: number
  /** Long press detection threshold in milliseconds */
  longPressDuration?: number
}
/**
 * Start monitoring FN key events
 *
 * @param config - Configuration options
 * @param callback - Callback function to receive events
 * @throws Error if monitor is already running or failed to start
 */
export declare function startMonitor(config: JsFnKeyConfig, callback: (event: { type: string; timestamp: number }) => void): void
/** Stop monitoring FN key events */
export declare function stopMonitor(): void
/**
 * Check if the monitor is currently running
 *
 * @returns true if running, false otherwise
 */
export declare function isMonitorRunning(): boolean
/**
 * Read the current Globe key FN usage type via HIToolbox TISGetFnUsageType.
 *
 * Return values: 0 = Do Nothing, 1 = Change Input Source,
 *                2 = Show Emoji & Symbols, 3 = Start Dictation
 *
 * This is the same value TextInputSwitcher reads to set isFnForEmoji.
 */
export declare function getFnUsageType(): number
/**
 * Set the Globe key FN usage type via HIToolbox TISUpdateFnUsageType.
 *
 * This is the same API System Preferences uses. It writes the preference
 * AND posts TIS change notifications so that TextInputSwitcher refreshes
 * its live isFnForEmoji state — no daemon restarts needed.
 *
 * @param value 0 = Do Nothing, 1 = Change Input Source,
 *              2 = Show Emoji & Symbols, 3 = Start Dictation
 */
export declare function setFnUsageType(value: number): void
